export interface University {
  id: string;
  name: string;
  location: string;
  overall: number; // calculated score out of 100
  citations: number; // 0-100
  employability: number; // 0-100
  intlStudents: number; // 0-100
  teaching: number; // 0-100
  research: number; // 0-100
  academicReputation?: number;
  employerReputation?: number;
  facultyStudentRatio?: number;
  subjects: string[];
  languages: string[];
  tuition: string; // e.g. "$3,500/year"
  description: string;
  history: number[]; // rank history, newest first (only years the backend actually reports)
  rankChange?: number | null; // real year-over-year rank movement (positive = climbed); null/undefined when unknown
  programs: string[];
  campusPhoto: string; // local path to campus photo
  logo?: string; // local path to university logo
  website?: string;
  hasMedicine: boolean;
  qsSubjectRankings?: {
    subject: string;
    worldRank: string;
    score: number;
  }[];
  // Optional flags used by filters. When missing, UI falls back to legacy ID-based rules.
  isPublic?: boolean;
  hasScholarship?: boolean;
  // ── Expanded admission-depth fields (PRD item 4) ──
  founded?: number;           // year the university was established
  studentCount?: number;      // total enrolled students (approx)
  facultyCount?: number;      // total academic staff
  acceptanceRate?: number;    // percentage 0-100
  applicationDeadline?: string; // e.g. "March 31, 2027"
  scholarshipDetails?: string;  // short description of available aid
}

// Legacy seed data retained for reference. Runtime university views now load
// live records through src/app/lib/universities.ts and UniversityDataProvider.
export const MOCK_UNIVERSITIES: University[] = [
  {
    id: "tsinghua",
    name: "Tsinghua University",
    location: "China",
    overall: 98.2,
    citations: 99.1,
    employability: 98.5,
    intlStudents: 72.4,
    teaching: 97.8,
    research: 99.3,
    subjects: ["Engineering", "Medicine", "Sciences", "Business"],
    languages: ["Chinese", "English"],
    tuition: "$4,800/year",
    description: "Tsinghua University is a major research university in Beijing, and a member of the elite C9 League. Established in 1911, it is consistently ranked as one of the top academic institutions in Asia.",
    history: [1, 1, 1, 2, 2],
    programs: ["MD Medicine (English-medium)", "M.Sc. Advanced Computing", "B.Eng. Mechanical Engineering", "MBA Global Business"],
    campusPhoto: "/university_images/China/Tsinghua University image.jpg",
    logo: "/university_images/China/Tsinghua University logo.jpg",
    hasMedicine: true,
    isPublic: true,
    hasScholarship: true,
    founded: 1911,
    studentCount: 47400,
    facultyCount: 3600,
    acceptanceRate: 2.1,
    applicationDeadline: "December 31, 2026",
    scholarshipDetails: "Chinese Government Scholarship (CSC), Tsinghua Excellence Award covering full tuition + stipend for top international applicants.",
  },
  {
    id: "nus",
    name: "National University of Singapore",
    location: "Singapore",
    overall: 97.9,
    citations: 98.4,
    employability: 99.0,
    intlStudents: 91.2,
    teaching: 96.2,
    research: 98.0,
    subjects: ["Medicine", "Engineering", "Sciences", "Business", "Humanities"],
    languages: ["English"],
    tuition: "$15,500/year",
    description: "The National University of Singapore is the national research university of Singapore. Founded in 1905 as a government medical school, it is the oldest higher education institution in Singapore.",
    history: [2, 2, 2, 1, 1],
    programs: ["Bachelor of Medicine & Surgery (MBBS)", "B.Sc. Data Science", "M.Sc. Finance", "Ph.D. Biomedical Sciences"],
    campusPhoto: "/university_images/Singapore/National University of Singapore image.jpg",
    logo: "/university_images/Singapore/National University of Singapore logo.jpg",
    hasMedicine: true,
    isPublic: true,
    hasScholarship: true,
    founded: 1905,
    studentCount: 40200,
    facultyCount: 2900,
    acceptanceRate: 6.5,
    applicationDeadline: "February 28, 2027",
    scholarshipDetails: "NUS Research Scholarship (PhD), ASEAN Undergraduate Scholarship for top ASEAN nationals covering full fees and living allowance.",
  },
  {
    id: "peking",
    name: "Peking University",
    location: "China",
    overall: 97.4,
    citations: 97.9,
    employability: 97.2,
    intlStudents: 74.8,
    teaching: 98.1,
    research: 98.5,
    subjects: ["Sciences", "Medicine", "Humanities", "Business"],
    languages: ["Chinese", "English"],
    tuition: "$4,500/year",
    description: "Peking University is a major Chinese research university in Beijing and a member of the elite C9 League. It was founded in 1898 as the Imperial University of Peking.",
    history: [3, 3, 3, 3, 3],
    programs: ["MD Clinical Medicine", "B.A. Chinese Literature", "Ph.D. Theoretical Physics"],
    campusPhoto: "/university_images/China/Peking University image.jpg",
    logo: "/university_images/China/Peking University logo.jpg",
    hasMedicine: true,
    isPublic: true,
    hasScholarship: true,
    founded: 1898,
    studentCount: 48000,
    facultyCount: 4100,
    acceptanceRate: 2.8,
    applicationDeadline: "January 15, 2027",
    scholarshipDetails: "Peking University Scholarship for International Students, covering tuition and dormitory fees for selected programs.",
  },
  {
    id: "tokyo",
    name: "The University of Tokyo",
    location: "Japan",
    overall: 96.8,
    citations: 96.2,
    employability: 98.1,
    intlStudents: 68.5,
    teaching: 97.5,
    research: 98.2,
    subjects: ["Engineering", "Medicine", "Sciences", "Humanities"],
    languages: ["Japanese", "English"],
    tuition: "$5,200/year",
    description: "The University of Tokyo is a premier public research university located in Bunkyo, Tokyo, Japan. Established in 1877, it is the first imperial university.",
    history: [4, 4, 4, 4, 4],
    programs: ["MD Medicine & Surgery", "B.Eng. Robotics & AI", "M.Sc. Earth Sciences"],
    campusPhoto: "/university_images/Japan/The University of Tokyo image.jpg",
    logo: "/university_images/Japan/The University of Tokyo logo.jpg",
    hasMedicine: true,
    isPublic: true,
    hasScholarship: true,
    founded: 1877,
    studentCount: 28000,
    facultyCount: 4000,
    acceptanceRate: 9.0,
    applicationDeadline: "November 30, 2026",
    scholarshipDetails: "MEXT Scholarship (Japanese Government) for international students covering tuition, travel, and monthly stipend.",
  },
  {
    id: "hku",
    name: "The University of Hong Kong",
    location: "Hong Kong",
    overall: 95.5,
    citations: 96.8,
    employability: 94.5,
    intlStudents: 94.0,
    teaching: 92.5,
    research: 94.2,
    subjects: ["Medicine", "Business", "Law", "Engineering", "Humanities"],
    languages: ["English"],
    tuition: "$21,000/year",
    description: "The University of Hong Kong is a public research university in Hong Kong. Founded in 1911, it is the oldest tertiary institution in Hong Kong.",
    history: [5, 6, 5, 5, 6],
    programs: ["Bachelor of Medicine and Bachelor of Surgery (MBBS)", "Bachelor of Laws (LLB)", "MBA"],
    campusPhoto: "/university_images/Hong-kong/The University of Hong Kong image.jpg",
    logo: "/university_images/Hong-kong/The University of Hong Kong logo.jpg",
    hasMedicine: true,
    founded: 1911,
    studentCount: 18000,
    facultyCount: 1400,
    acceptanceRate: 12.5,
    applicationDeadline: "March 31, 2027",
    scholarshipDetails: "HKU Presidential PhD Scholarship and HKSAR Government bursaries for eligible international undergraduates.",
  },
  {
    id: "ntu",
    name: "Nanyang Technological University",
    location: "Singapore",
    overall: 95.2,
    citations: 97.5,
    employability: 93.8,
    intlStudents: 88.5,
    teaching: 91.0,
    research: 95.1,
    subjects: ["Engineering", "Sciences", "Business", "Medicine"],
    languages: ["English"],
    tuition: "$14,800/year",
    description: "NTU Singapore is a research-intensive public university consistently ranked among the world's best. It houses elite schools in engineering, science, business, and medicine.",
    history: [6, 5, 6, 6, 5],
    programs: ["B.Eng. Computer Science", "MBBS Medicine (Imperial College Partner)", "MBA Strategy"],
    campusPhoto: "/university_images/Singapore/Nanyang Technological University image.jpg",
    logo: "/university_images/Singapore/Nanyang Technological University logo.jpg",
    hasMedicine: true,
    founded: 1991,
    studentCount: 33500,
    facultyCount: 2200,
    acceptanceRate: 8.0,
    applicationDeadline: "February 15, 2027",
    scholarshipDetails: "NTU Research Scholarship and ASEAN undergraduate scholarships for high-performing applicants.",
  },
  {
    id: "snu",
    name: "Seoul National University",
    location: "South Korea",
    overall: 94.1,
    citations: 92.4,
    employability: 96.5,
    intlStudents: 59.8,
    teaching: 95.0,
    research: 95.8,
    subjects: ["Sciences", "Medicine", "Engineering", "Business", "Humanities"],
    languages: ["Korean", "English"],
    tuition: "$6,500/year",
    description: "Seoul National University is a national research university located in Seoul, South Korea. Founded in 1946, it is widely considered the most prestigious university in the country.",
    history: [7, 7, 7, 7, 7],
    programs: ["MD Doctor of Medicine", "B.Sc. Semiconductor Engineering", "Global MBA"],
    campusPhoto: "/university_images/South-Korea/Seoul National University image.jpg",
    logo: "/university_images/South-Korea/Seoul National University logo.jpg",
    hasMedicine: true,
    founded: 1946,
    studentCount: 28600,
    facultyCount: 2100,
    acceptanceRate: 3.5,
    applicationDeadline: "January 31, 2027",
    scholarshipDetails: "Korean Government Scholarship Program (NIIED-GKS) for international students. SNU also offers need-based grants.",
  },
  {
    id: "kyoto",
    name: "Kyoto University",
    location: "Japan",
    overall: 93.6,
    citations: 91.5,
    employability: 95.2,
    intlStudents: 61.2,
    teaching: 96.0,
    research: 95.5,
    subjects: ["Sciences", "Engineering", "Medicine", "Humanities"],
    languages: ["Japanese", "English"],
    tuition: "$5,200/year",
    description: "Kyoto University is a public research university in Kyoto, Japan. Founded in 1897, it is the second oldest imperial university and has produced numerous Nobel laureates.",
    history: [8, 8, 8, 8, 8],
    programs: ["MD Medicine", "B.Sc. Chemistry", "Ph.D. Quantum Science"],
    campusPhoto: "/university_images/Japan/Kyoto University image.jpg",
    logo: "/university_images/Japan/Kyoto University logo.jpg",
    hasMedicine: true,
    founded: 1897,
    studentCount: 22000,
    facultyCount: 2800,
    acceptanceRate: 7.2,
    applicationDeadline: "December 15, 2026",
    scholarshipDetails: "MEXT Scholarship (Japanese Government) and Kyoto University Scholarship for international research students.",
  },
  {
    id: "kaist",
    name: "KAIST",
    location: "South Korea",
    overall: 92.8,
    citations: 95.1,
    employability: 94.0,
    intlStudents: 62.5,
    teaching: 91.2,
    research: 94.8,
    subjects: ["Engineering", "Sciences", "Business"],
    languages: ["English", "Korean"],
    tuition: "$7,000/year",
    description: "KAIST (Korea Advanced Institute of Science and Technology) is the first and top research-oriented science and engineering institution in South Korea.",
    history: [9, 10, 9, 10, 9],
    programs: ["B.Sc. Electrical Engineering", "M.Sc. Robotics", "Ph.D. Aerospace Systems"],
    campusPhoto: "/university_images/South-Korea/KAIST image.jpg",
    logo: "/university_images/South-Korea/KAIST logo.jpg",
    hasMedicine: false
  },
  {
    id: "cuhk",
    name: "The Chinese University of Hong Kong",
    location: "Hong Kong",
    overall: 92.1,
    citations: 94.8,
    employability: 91.0,
    intlStudents: 89.2,
    teaching: 88.5,
    research: 91.8,
    subjects: ["Medicine", "Sciences", "Social Sciences", "Business"],
    languages: ["English", "Chinese"],
    tuition: "$19,500/year",
    description: "CUHK is a top-ranked public research university in Shatin, Hong Kong. Established in 1963, it operates on a unique collegiate system and is highly bilingual.",
    history: [10, 9, 10, 9, 10],
    programs: ["MBChB Doctor of Medicine", "B.Sc. Quantitative Finance", "B.Eng. Bioengineering"],
    campusPhoto: "/university_images/Hong-kong/The Chinese University of Hong Kong image.jpg",
    logo: "/university_images/Hong-kong/The Chinese University of Hong Kong logo.jpg",
    hasMedicine: true
  },
  {
    id: "tashkent-med",
    name: "Tashkent Medical Academy",
    location: "Uzbekistan",
    overall: 71.4,
    citations: 68.2,
    employability: 74.5,
    intlStudents: 85.0,
    teaching: 72.8,
    research: 66.4,
    subjects: ["Medicine", "Sciences"],
    languages: ["English", "Russian", "Uzbek"],
    tuition: "$3,800/year",
    description: "Tashkent Medical Academy is the premier medical institution in Uzbekistan. Established in 1919 and reorganized in 2005, it hosts over 2,000 international students studying medical programs.",
    history: [11, 14, 18, 22, 30],
    programs: ["General Medicine (MD - English-medium)", "Pediatric Medicine", "Preventive Medicine", "M.Sc. Cardiovascular Surgery"],
    campusPhoto: "/university_images/Uzbekistan/Tashkent Medical Academy image.jpg",
    logo: "/university_images/Uzbekistan/Tashkent Medical Academy logo.jpg",
    hasMedicine: true,
    isPublic: true,
    hasScholarship: true
  },
  {
    id: "fergana-med",
    name: "Fergana State University Medical Centre",
    location: "Uzbekistan",
    overall: 69.8,
    citations: 65.5,
    employability: 71.2,
    intlStudents: 88.6,
    teaching: 74.0,
    research: 62.8,
    subjects: ["Medicine"],
    languages: ["English", "Uzbek", "Russian"],
    tuition: "$3,400/year",
    description: "Located in the scenic Fergana Valley, Fergana State Medical Faculty provides high-quality English-medium MBBS/MD courses. It is certified by WHO, NMC, and is a major hub for South Asian students.",
    history: [12, 16, 21, 28, 38],
    programs: ["General Medicine (MD - 6 Years English-medium)", "Pharmacy (B.Pharm)", "Nursing"],
    campusPhoto: "/university_images/Uzbekistan/Fergana State University Medical Centre image.jpg",
    logo: "/university_images/Uzbekistan/Fergana State University Medical Centre logo.jpg",
    hasMedicine: true
  },
  {
    id: "samarkand-med",
    name: "Samarkand State Medical University",
    location: "Uzbekistan",
    overall: 69.1,
    citations: 64.8,
    employability: 70.8,
    intlStudents: 87.2,
    teaching: 72.5,
    research: 61.2,
    subjects: ["Medicine", "Sciences"],
    languages: ["English", "Uzbek", "Russian"],
    tuition: "$3,500/year",
    description: "Established in 1930, Samarkand State Medical University is the oldest medical university in Central Asia. It features advanced digital medical campuses and clinic training units.",
    history: [13, 15, 20, 26, 35],
    programs: ["General Medicine (MD)", "Dentistry", "Pharmacy", "Postgraduate Medical Specialties"],
    campusPhoto: "/university_images/Uzbekistan/Samarkand State Medical University image.jpg",
    logo: "/university_images/Uzbekistan/Samarkand State Medical University logo.jpg",
    hasMedicine: true,
    isPublic: true,
    hasScholarship: true
  },
  {
    id: "tashkent-pediatric",
    name: "Tashkent Pediatric Medical Institute",
    location: "Uzbekistan",
    overall: 68.2,
    citations: 63.8,
    employability: 69.5,
    intlStudents: 79.4,
    teaching: 73.1,
    research: 60.5,
    subjects: ["Medicine"],
    languages: ["Russian", "Uzbek", "English"],
    tuition: "$3,600/year",
    description: "A specialized medical institution focusing on pediatric medicine, pediatric surgery, and public health in Uzbekistan. Affiliated with top children's hospitals in Tashkent.",
    history: [14, 18, 23, 29, 39],
    programs: ["Pediatric Medicine (MD)", "General Medicine", "B.Sc. Professional Nursing"],
    campusPhoto: "/university_images/Uzbekistan/Tashkent Pediatric Medical Institute image.jpg",
    logo: "/university_images/Uzbekistan/Tashkent Pediatric Medical Institute logo.jpg",
    hasMedicine: true
  },
  {
    id: "bukhara-med",
    name: "Bukhara State Medical Institute",
    location: "Uzbekistan",
    overall: 67.5,
    citations: 62.0,
    employability: 68.0,
    intlStudents: 84.5,
    teaching: 71.8,
    research: 59.4,
    subjects: ["Medicine"],
    languages: ["English", "Russian", "Uzbek"],
    tuition: "$3,300/year",
    description: "Named after Abu Ali ibn Sino (Avicenna), Bukhara State Medical Institute boasts modern anatomy labs and international collaborations with medical universities across Europe and Asia.",
    history: [15, 19, 25, 32, 42],
    programs: ["MD General Medicine (English-medium)", "BDS Dentistry", "Medical Prophylactics"],
    campusPhoto: "/university_images/Uzbekistan/Bukhara State Medical Institute image.jpg",
    logo: "/university_images/Uzbekistan/Bukhara State Medical Institute logo.jpg",
    hasMedicine: true
  },
  {
    id: "fudan",
    name: "Fudan University",
    location: "China",
    overall: 91.5,
    citations: 92.1,
    employability: 91.4,
    intlStudents: 70.2,
    teaching: 91.8,
    research: 92.5,
    subjects: ["Sciences", "Medicine", "Humanities", "Business"],
    languages: ["Chinese", "English"],
    tuition: "$4,200/year",
    description: "Fudan University is a prestigious public research university in Shanghai, China. Known for its liberal academic atmosphere and top-tier humanities and medicine.",
    history: [16, 11, 11, 11, 11],
    programs: ["MD Clinical Medicine", "B.A. Economics", "MBA"],
    campusPhoto: "/university_images/China/Fudan University image.jpg",
    logo: "/university_images/China/Fudan University logo.jpg",
    hasMedicine: true
  },
  {
    id: "zhejiang",
    name: "Zhejiang University",
    location: "China",
    overall: 90.8,
    citations: 91.8,
    employability: 90.2,
    intlStudents: 69.4,
    teaching: 91.0,
    research: 92.0,
    subjects: ["Engineering", "Medicine", "Sciences", "Business"],
    languages: ["Chinese", "English"],
    tuition: "$4,300/year",
    description: "Zhejiang University is an elite university in Hangzhou, China. Established in 1897, it is one of China's oldest, most prestigious institutions of higher education.",
    history: [17, 12, 12, 12, 12],
    programs: ["B.Eng. Computer Engineering", "MBBS Medicine", "Ph.D. Materials Science"],
    campusPhoto: "/university_images/China/Zhejiang University image.jpg",
    logo: "/university_images/China/Zhejiang University logo.jpg",
    hasMedicine: true
  },
  {
    id: "ustc",
    name: "University of Science and Technology of China",
    location: "China",
    overall: 90.1,
    citations: 94.2,
    employability: 87.5,
    intlStudents: 42.0,
    teaching: 92.4,
    research: 91.0,
    subjects: ["Sciences", "Engineering"],
    languages: ["Chinese", "English"],
    tuition: "$4,000/year",
    description: "USTC is a national research university in Hefei, China, under the direct leadership of the Chinese Academy of Sciences. It is renowned for high-impact physics and chemistry.",
    history: [18, 13, 13, 14, 13],
    programs: ["B.Sc. Physics", "B.Sc. Chemistry", "M.Sc. Quantum Computing"],
    campusPhoto: "/university_images/China/University of Science and Technology of China image.jpg",
    logo: "/university_images/China/University of Science and Technology of China logo.jpg",
    hasMedicine: false
  },
  {
    id: "titech",
    name: "Tokyo Institute of Technology",
    location: "Japan",
    overall: 89.2,
    citations: 89.0,
    employability: 91.5,
    intlStudents: 60.1,
    teaching: 88.2,
    research: 89.4,
    subjects: ["Engineering", "Sciences"],
    languages: ["Japanese", "English"],
    tuition: "$5,200/year",
    description: "Tokyo Tech is the largest institution for higher education in Japan dedicated to science and technology and is at the forefront of nanotechnology and robotics research.",
    history: [19, 17, 16, 17, 16],
    programs: ["B.Eng. Robotics", "M.Eng. Mechanical Engineering", "M.Sc. Materials Science"],
    campusPhoto: "/university_images/Japan/Tokyo Institute of Technolog image.jpg",
    logo: "/university_images/Japan/Tokyo Institute of Technolog logo.jpg",
    hasMedicine: false
  },
  {
    id: "osaka",
    name: "Osaka University",
    location: "Japan",
    overall: 88.9,
    citations: 87.2,
    employability: 91.0,
    intlStudents: 59.5,
    teaching: 89.8,
    research: 89.0,
    subjects: ["Sciences", "Medicine", "Engineering", "Humanities"],
    languages: ["Japanese", "English"],
    tuition: "$5,200/year",
    description: "Osaka University is a leading public research university located in Osaka, Japan. It is one of Japan's Imperial Universities and is highly ranked for biology and dentistry.",
    history: [20, 19, 19, 18, 19],
    programs: ["MD Medicine", "Dentistry (DDS)", "B.Sc. Biotechnology"],
    campusPhoto: "/university_images/Japan/Osaka University image.jpg",
    logo: "/university_images/Japan/Osaka University logo.jpg",
    hasMedicine: true
  },
  {
    id: "yonsei",
    name: "Yonsei University",
    location: "South Korea",
    overall: 88.1,
    citations: 86.8,
    employability: 92.4,
    intlStudents: 78.5,
    teaching: 86.5,
    research: 87.8,
    subjects: ["Sciences", "Medicine", "Business", "Humanities", "Engineering"],
    languages: ["Korean", "English"],
    tuition: "$8,500/year",
    description: "Yonsei University is a private research university in Seoul, South Korea. It is one of Korea's three prestigious 'SKY' universities and boasts one of the top medical schools.",
    history: [21, 22, 24, 25, 23],
    programs: ["MD Medical Sciences", "Undergraduate Global Studies", "MBA Business Administration"],
    campusPhoto: "/university_images/South-Korea/Yonsei University image.jpg",
    logo: "/university_images/South-Korea/Yonsei University logo.jpg",
    hasMedicine: true,
    isPublic: false
  },
  {
    id: "korea-univ",
    name: "Korea University",
    location: "South Korea",
    overall: 87.5,
    citations: 86.0,
    employability: 93.1,
    intlStudents: 76.2,
    teaching: 85.8,
    research: 87.0,
    subjects: ["Sciences", "Medicine", "Business", "Engineering", "Law"],
    languages: ["Korean", "English"],
    tuition: "$8,200/year",
    description: "Korea University is a top-tier private research university in Seoul, South Korea, founded in 1905. Famous for its highly selective law, business, and medical programs.",
    history: [22, 21, 23, 23, 22],
    programs: ["MD Medicine", "B.Sc. Cyber Security", "BBA Business Administration"],
    campusPhoto: "/university_images/South-Korea/Korea University image.jpg",
    logo: "/university_images/South-Korea/Korea University logo.jpg",
    hasMedicine: true,
    isPublic: false
  },
  {
    id: "cuhk-sz",
    name: "CUHK Shenzhen",
    location: "China",
    overall: 86.8,
    citations: 88.2,
    employability: 85.5,
    intlStudents: 55.4,
    teaching: 87.2,
    research: 86.0,
    subjects: ["Engineering", "Business", "Sciences"],
    languages: ["English", "Chinese"],
    tuition: "$14,000/year",
    description: "An expansion of the Chinese University of Hong Kong in Shenzhen, providing highly globalized curriculums in data sciences, finance, and engineering in mainland China.",
    history: [23, 27, 32, 40, 52],
    programs: ["B.Sc. Financial Engineering", "B.Eng. Computer Science", "M.Sc. Data Science"],
    campusPhoto: "/university_images/China/CUHK Shenzhen image.jpg",
    logo: "/university_images/China/CUHK Shenzhen logo.jpg",
    hasMedicine: false
  },
  {
    id: "tsukuba",
    name: "University of Tsukuba",
    location: "Japan",
    overall: 85.2,
    citations: 83.5,
    employability: 84.8,
    intlStudents: 64.0,
    teaching: 88.0,
    research: 84.2,
    subjects: ["Sciences", "Medicine", "Humanities"],
    languages: ["Japanese", "English"],
    tuition: "$5,200/year",
    description: "The University of Tsukuba is a leading research university in Tsukuba Science City, Ibaraki. It is highly regarded for biology, sports science, and medicine.",
    history: [24, 25, 26, 24, 25],
    programs: ["MD Medical Sciences", "B.Sc. Interdisciplinary Science", "M.Sc. Sports Medicine"],
    campusPhoto: "/university_images/Japan/University of Tsukuba image.jpg",
    logo: "/university_images/Japan/University of Tsukuba logo.jpg",
    hasMedicine: true
  },
  {
    id: "iit-bombay",
    name: "Indian Institute of Technology Bombay",
    location: "India",
    overall: 84.9,
    citations: 89.4,
    employability: 92.5,
    intlStudents: 15.2,
    teaching: 79.8,
    research: 86.2,
    subjects: ["Engineering", "Sciences"],
    languages: ["English"],
    tuition: "$2,800/year",
    description: "IIT Bombay is a leading public research university located in Mumbai, India. It is a premier institute of national importance, famous for its selective engineering entrance exams.",
    history: [25, 23, 22, 21, 21],
    programs: ["B.Tech. Computer Science", "B.Tech. Aerospace Engineering", "M.Tech. Microelectronics"],
    campusPhoto: "/university_images/India/IIT BOMBAY image.jpg",
    logo: "/university_images/India/IIT BOMBAY logo.jpg",
    hasMedicine: false
  },
  {
    id: "iit-delhi",
    name: "Indian Institute of Technology Delhi",
    location: "India",
    overall: 84.2,
    citations: 88.1,
    employability: 91.8,
    intlStudents: 14.8,
    teaching: 78.5,
    research: 85.5,
    subjects: ["Engineering", "Sciences"],
    languages: ["English"],
    tuition: "$2,800/year",
    description: "IIT Delhi is a prestigious engineering and research institution in New Delhi, India. It offers highly competitive programs and carries a massive reputation globally.",
    history: [26, 24, 25, 26, 24],
    programs: ["B.Tech. Electrical Engineering", "M.Tech. Artificial Intelligence", "Ph.D. Renewable Energy"],
    campusPhoto: "/university_images/India/IIT Delhi image.jpg",
    logo: "/university_images/India/IIT Delhi logo.jpg",
    hasMedicine: false
  },
  {
    id: "iisc",
    name: "Indian Institute of Science",
    location: "India",
    overall: 83.8,
    citations: 99.8,
    employability: 72.4,
    intlStudents: 12.0,
    teaching: 84.5,
    research: 89.2,
    subjects: ["Sciences", "Engineering"],
    languages: ["English"],
    tuition: "$1,800/year",
    description: "IISc Bangalore is a premier research institute for advanced scientific research and education in India. It holds the world's highest citation-per-faculty score in recent indicators.",
    history: [27, 26, 27, 27, 28],
    programs: ["Bachelor of Science (Research)", "M.Tech. Nanotechnology", "Ph.D. Physics / Biochemistry"],
    campusPhoto: "/university_images/India/indian institute of science image.jpg",
    logo: "/university_images/India/indian institute of science logo.jpg",
    hasMedicine: false
  },
  {
    id: "taiwan-univ",
    name: "National Taiwan University",
    location: "Taiwan",
    overall: 83.1,
    citations: 82.5,
    employability: 88.0,
    intlStudents: 48.2,
    teaching: 85.0,
    research: 84.8,
    subjects: ["Engineering", "Medicine", "Sciences", "Business", "Humanities"],
    languages: ["Chinese", "English"],
    tuition: "$3,900/year",
    description: "NTU is the prestigious national university of Taiwan located in Taipei. It has played an instrumental role in the economic development and semiconductor boom of Taiwan.",
    history: [28, 28, 29, 28, 27],
    programs: ["MD Clinical Medicine", "B.Sc. Electrical Engineering", "Global MBA"],
    campusPhoto: "/university_images/Taiwan/National Taiwan University image.jpg",
    logo: "/university_images/Taiwan/National Taiwan University logo.jpg",
    hasMedicine: true
  },
  {
    id: "malaya",
    name: "Universiti Malaya",
    location: "Malaysia",
    overall: 82.5,
    citations: 81.2,
    employability: 85.4,
    intlStudents: 75.8,
    teaching: 82.1,
    research: 83.0,
    subjects: ["Medicine", "Sciences", "Engineering", "Business"],
    languages: ["English", "Malay"],
    tuition: "$6,200/year",
    description: "Universiti Malaya is the oldest and highest-ranking university in Malaysia. Its campus sits in southwest Kuala Lumpur, featuring a massive specialized medical medical complex.",
    history: [29, 30, 31, 30, 29],
    programs: ["MBBS Doctor of Medicine", "B.Eng. Civil Engineering", "M.Sc. Business Analytics"],
    campusPhoto: "/university_images/Malaysia/Universiti Malaya image.jpg",
    logo: "/university_images/Malaysia/Universiti Malaya logo.jpg",
    hasMedicine: true,
    isPublic: true,
    hasScholarship: true
  },
  {
    id: "chula",
    name: "Chulalongkorn University",
    location: "Thailand",
    overall: 81.0,
    citations: 78.4,
    employability: 84.1,
    intlStudents: 38.6,
    teaching: 83.5,
    research: 80.8,
    subjects: ["Medicine", "Sciences", "Business", "Engineering"],
    languages: ["Thai", "English"],
    tuition: "$5,800/year",
    description: "Chulalongkorn University is the oldest and most prestigious university in Thailand. It has a high reputation for medical clinical research and public health.",
    history: [30, 31, 33, 34, 32],
    programs: ["Doctor of Medicine (English-medium)", "B.Sc. Nano-Engineering", "BBA International Business"],
    campusPhoto: "/university_images/Thailand/Chulalongkorn University image.jpg",
    logo: "/university_images/Thailand/Chulalongkorn University logo.jpg",
    hasMedicine: true
  },
  {
    id: "tashkent-state",
    name: "National University of Uzbekistan",
    location: "Uzbekistan",
    overall: 65.2,
    citations: 58.4,
    employability: 62.1,
    intlStudents: 32.5,
    teaching: 71.0,
    research: 61.8,
    subjects: ["Sciences", "Humanities", "Business"],
    languages: ["Uzbek", "Russian", "English"],
    tuition: "$2,200/year",
    description: "The National University of Uzbekistan is the oldest and largest university in Uzbekistan. Established in 1918, it offers deep training in physics, mathematics, and philosophy.",
    history: [31, 38, 48, 56, 70],
    programs: ["B.Sc. Theoretical Mathematics", "B.Sc. Applied Physics", "M.A. Linguistics"],
    campusPhoto: "/university_images/Uzbekistan/National University of Uzbekistan image.jpg",
    logo: "/university_images/Uzbekistan/National University of Uzbekistan logo.jpg",
    hasMedicine: false
  },
  {
    id: "tashkent-polytech",
    name: "Tashkent State Technical University",
    location: "Uzbekistan",
    overall: 63.8,
    citations: 56.2,
    employability: 64.0,
    intlStudents: 28.6,
    teaching: 69.5,
    research: 60.2,
    subjects: ["Engineering"],
    languages: ["Uzbek", "Russian"],
    tuition: "$2,400/year",
    description: "Tashkent State Technical University is one of the oldest technical universities in Central Asia, preparing elite engineering minds for industrial machinery and energy grids.",
    history: [32, 40, 50, 62, 78],
    programs: ["B.Eng. Mechanical Engineering", "B.Eng. Petroleum & Gas", "M.Eng. Power System Grids"],
    campusPhoto: "/university_images/Uzbekistan/Tashkent State Technical University image.jpg",
    logo: "/university_images/Uzbekistan/Tashkent State Technical University logo.jpg",
    hasMedicine: false
  },
  {
    id: "tashkent-webster",
    name: "Webster University in Tashkent",
    location: "Uzbekistan",
    overall: 62.5,
    citations: 54.0,
    employability: 70.2,
    intlStudents: 45.8,
    teaching: 68.0,
    research: 50.4,
    subjects: ["Business", "Humanities"],
    languages: ["English"],
    tuition: "$4,200/year",
    description: "Webster University in Tashkent is an official American branch campus, delivering full US-accredited business administration, media, and education degrees in Central Asia.",
    history: [33, 42, 55, 75, 95],
    programs: ["Bachelor of Business Administration (BBA)", "BA Media Studies", "MA TESOL (Applied Linguistics)"],
    campusPhoto: "/university_images/Uzbekistan/Webster University in Tashkent image.jpg",
    logo: "/university_images/Uzbekistan/Webster University in Tashkent logo.jpg",
    hasMedicine: false,
    isPublic: false
  },
  {
    id: "fergana-polytech",
    name: "Fergana Polytechnic Institute",
    location: "Uzbekistan",
    overall: 61.2,
    citations: 53.8,
    employability: 59.5,
    intlStudents: 21.0,
    teaching: 67.2,
    research: 58.5,
    subjects: ["Engineering"],
    languages: ["Uzbek", "Russian"],
    tuition: "$2,000/year",
    description: "An engineering focused institute located in Fergana, providing essential training in civil engineering, textile production, and chemical processing.",
    history: [34, 45, 58, 71, 88],
    programs: ["B.Eng. Civil Construction", "B.Eng. Textile Engineering", "B.Sc. Chemical Technology"],
    campusPhoto: "/university_images/Uzbekistan/Fergana Polytechnic Institute image.jpg",
    logo: "/university_images/Uzbekistan/Fergana Polytechnic Institute logo.jpg",
    hasMedicine: false
  },
  {
    id: "akfa-univ",
    name: "Central Asian University (former AKFA)",
    location: "Uzbekistan",
    overall: 60.5,
    citations: 51.2,
    employability: 68.5,
    intlStudents: 38.4,
    teaching: 66.8,
    research: 48.0,
    subjects: ["Medicine", "Business", "Engineering"],
    languages: ["English"],
    tuition: "$5,500/year",
    description: "A private university in Tashkent offering dynamic curricula in collaboration with medical centers in Turkey and South Korea. One of the first modern private medical schools.",
    history: [35, 48, 62, 85, 100],
    programs: ["MD Doctor of Medicine (English)", "B.Sc. Computer Science", "BBA Finance"],
    campusPhoto: "/university_images/Uzbekistan/Central Asian University (former AKFA) image.jpg",
    logo: "/university_images/Uzbekistan/Central Asian University (former AKFA) logo.jpg",
    hasMedicine: true,
    isPublic: false,
    hasScholarship: true
  },
  {
    id: "hokkaido",
    name: "Hokkaido University",
    location: "Japan",
    overall: 80.5,
    citations: 77.2,
    employability: 81.4,
    intlStudents: 52.8,
    teaching: 84.1,
    research: 79.5,
    subjects: ["Sciences", "Medicine", "Engineering"],
    languages: ["Japanese", "English"],
    tuition: "$5,200/year",
    description: "Hokkaido University is a leading Japanese national university, famous for agricultural sciences, environmental engineering, and its beautiful historic campus in Sapporo.",
    history: [36, 35, 34, 33, 33],
    programs: ["MD Clinical Medicine", "B.Sc. Agriculture Science", "M.Sc. Environmental Biology"],
    campusPhoto: "/university_images/Japan/Hokkaido University image.jpg",
    logo: "/university_images/Japan/Hokkaido University logo.jpg",
    hasMedicine: true
  },
  {
    id: "kyushu",
    name: "Kyushu University",
    location: "Japan",
    overall: 79.8,
    citations: 76.5,
    employability: 82.0,
    intlStudents: 54.0,
    teaching: 83.2,
    research: 78.4,
    subjects: ["Sciences", "Medicine", "Engineering"],
    languages: ["Japanese", "English"],
    tuition: "$5,200/year",
    description: "Kyushu University in Fukuoka is one of Japan's seven Imperial Universities. It hosts top-tier programs in engineering, biotechnology, and health sciences.",
    history: [37, 36, 35, 35, 34],
    programs: ["MD Medical Surgery", "B.Eng. Materials Science", "M.Sc. Marine Biology"],
    campusPhoto: "/university_images/Japan/Kyushu University image.jpg",
    logo: "/university_images/Japan/Kyushu University logo.jpg",
    hasMedicine: true
  },
  {
    id: "mahidol",
    name: "Mahidol University",
    location: "Thailand",
    overall: 78.9,
    citations: 79.2,
    employability: 74.0,
    intlStudents: 29.4,
    teaching: 81.8,
    research: 75.2,
    subjects: ["Medicine", "Sciences"],
    languages: ["Thai", "English"],
    tuition: "$6,500/year",
    description: "Mahidol University began as a hospital-affiliated school in 1888. It is Thailand's highest ranked medical and health science institution.",
    history: [38, 37, 36, 37, 36],
    programs: ["MD Medicine (Siriraj Hospital)", "B.Sc. Medical Technology", "Ph.D. Virology"],
    campusPhoto: "/university_images/Thailand/Mahidol University image.jpg",
    logo: "/university_images/Thailand/Mahidol University logo.jpg",
    hasMedicine: true
  },
  {
    id: "universitas-indonesia",
    name: "Universitas Indonesia",
    location: "Indonesia",
    overall: 78.2,
    citations: 71.0,
    employability: 82.5,
    intlStudents: 25.4,
    teaching: 83.0,
    research: 74.8,
    subjects: ["Medicine", "Sciences", "Business", "Humanities"],
    languages: ["Indonesian", "English"],
    tuition: "$4,500/year",
    description: "Universitas Indonesia is a state university in Depok, West Java and Jakarta. It is the oldest modern higher education institution in Indonesia.",
    history: [39, 39, 40, 42, 45],
    programs: ["MD General Medicine (International)", "Bachelor of Economics", "B.Eng. Electrical Engineering"],
    campusPhoto: "/university_images/Indonesia/Universitas Indonesia image.jpg",
    logo: "/university_images/Indonesia/Universitas Indonesia logo.jpg",
    hasMedicine: true
  },
  {
    id: "gadjah-mada",
    name: "Universitas Gadjah Mada",
    location: "Indonesia",
    overall: 77.5,
    citations: 69.4,
    employability: 83.1,
    intlStudents: 22.8,
    teaching: 82.4,
    research: 73.5,
    subjects: ["Medicine", "Sciences", "Engineering", "Business"],
    languages: ["Indonesian", "English"],
    tuition: "$4,000/year",
    description: "UGM is a premier public research university located in Yogyakarta, Indonesia. Founded in 1949, it is the largest and most historically significant university in Indonesia.",
    history: [40, 41, 41, 44, 46],
    programs: ["MD Clinical Medicine", "B.Eng. Mechanical Engineering", "B.Sc. Pharmacy"],
    campusPhoto: "/university_images/Indonesia/Universitas Gadjah Mada image.jpg",
    logo: "/university_images/Indonesia/Universitas Gadjah Mada logo.jpg",
    hasMedicine: true
  },
  {
    id: "lomonosov-tashkent",
    name: "Lomonosov Moscow State University Branch in Tashkent",
    location: "Uzbekistan",
    overall: 60.1,
    citations: 50.8,
    employability: 65.2,
    intlStudents: 15.6,
    teaching: 67.5,
    research: 57.2,
    subjects: ["Sciences", "Business"],
    languages: ["Russian"],
    tuition: "$2,800/year",
    description: "A branch campus of the elite Lomonosov Moscow State University, providing high-quality Russian instruction in applied mathematics, psychology, and management in Tashkent.",
    history: [41, 49, 61, 74, 90],
    programs: ["B.Sc. Applied Mathematics & Informatics", "B.Sc. Psychology", "M.Sc. Management"],
    campusPhoto: "/university_images/Uzbekistan/Lomonosov Moscow State University Branch in Tashkent image.jpg",
    logo: "/university_images/Uzbekistan/Lomonosov Moscow State University Branch in Tashkent logo.jpg",
    hasMedicine: false
  },
  {
    id: "plekhanov-tashkent",
    name: "Plekhanov Russian University of Economics (Tashkent Branch)",
    location: "Uzbekistan",
    overall: 59.2,
    citations: 48.5,
    employability: 67.8,
    intlStudents: 22.4,
    teaching: 65.0,
    research: 52.0,
    subjects: ["Business"],
    languages: ["Russian", "English"],
    tuition: "$3,000/year",
    description: "The first branch of a foreign university opened in Uzbekistan (established in 2001). It has trained thousands of economists and financial analytics for Central Asia.",
    history: [42, 52, 65, 80, 105],
    programs: ["B.Sc. Economics & Business Analytics", "B.Sc. Finance", "MBA Digital Business"],
    campusPhoto: "/university_images/Uzbekistan/Plekhanov Russian University of Economics (Tashkent Branch) image.jpg",
    logo: "/university_images/Uzbekistan/Plekhanov Russian University of Economics (Tashkent Branch) logo.jpg",
    hasMedicine: false
  },
  {
    id: "nankai",
    name: "Nankai University",
    location: "China",
    overall: 76.8,
    citations: 82.0,
    employability: 72.8,
    intlStudents: 41.5,
    teaching: 79.2,
    research: 75.8,
    subjects: ["Sciences", "Business", "Medicine", "Humanities"],
    languages: ["Chinese", "English"],
    tuition: "$3,800/year",
    description: "Nankai University is a public research university in Tianjin, China. Founded in 1919 by educators Yan Xiu and Zhang Boling, it is famous for economics and chemistry.",
    history: [43, 42, 42, 41, 40],
    programs: ["B.Sc. Chemistry", "MD General Medicine", "B.A. Economics"],
    campusPhoto: "/university_images/China/Nankai University image.jpg",
    logo: "/university_images/China/Nankai University logo.jpg",
    hasMedicine: true
  },
  {
    id: "wuhan",
    name: "Wuhan University",
    location: "China",
    overall: 76.2,
    citations: 80.5,
    employability: 74.0,
    intlStudents: 50.8,
    teaching: 78.4,
    research: 76.0,
    subjects: ["Medicine", "Sciences", "Engineering", "Humanities"],
    languages: ["Chinese", "English"],
    tuition: "$4,000/year",
    description: "Wuhan University in Wuhan, Hubei, is one of China's most picturesque campuses. Founded in 1893, it has exceptionally strong clinical medicine and geography programs.",
    history: [44, 43, 44, 43, 41],
    programs: ["MBBS Doctor of Medicine", "B.Sc. Geospatial Engineering", "Ph.D. Virology"],
    campusPhoto: "/university_images/China/Wuhan University image.jpg",
    logo: "/university_images/China/Wuhan University logo.jpg",
    hasMedicine: true
  },
  {
    id: "saitama",
    name: "Saitama University",
    location: "Japan",
    overall: 75.8,
    citations: 72.4,
    employability: 73.2,
    intlStudents: 31.0,
    teaching: 81.5,
    research: 74.0,
    subjects: ["Sciences", "Engineering", "Humanities"],
    languages: ["Japanese"],
    tuition: "$5,200/year",
    description: "Saitama University is a Japanese national university located in a suburban area of Saitama City, offering highly practical science and engineering studies.",
    history: [45, 46, 45, 46, 44],
    programs: ["B.Eng. Electrical Engineering", "B.Sc. Mathematical Physics", "M.A. Global Sociology"],
    campusPhoto: "/university_images/Japan/Saitama University image.jpg",
    logo: "/university_images/Japan/Saitama University logo.jpg",
    hasMedicine: false
  },
  {
    id: "tsinghua-sz",
    name: "Tsinghua Shenzhen International Graduate School",
    location: "China",
    overall: 75.2,
    citations: 84.8,
    employability: 70.1,
    intlStudents: 42.6,
    teaching: 72.8,
    research: 76.5,
    subjects: ["Engineering", "Sciences", "Business"],
    languages: ["English", "Chinese"],
    tuition: "$6,500/year",
    description: "Established in 2001, this graduate school offers top-tier research collaborations in environmental technology, financial technology, and biotechnology.",
    history: [46, 44, 43, 45, 47],
    programs: ["M.Sc. Environmental Technology", "M.Sc. Financial Technology", "M.Sc. Advanced Materials"],
    campusPhoto: "/university_images/China/Tsinghua Shenzhen International Graduate School image.jpg",
    logo: "/university_images/China/Tsinghua Shenzhen International Graduate School logo.jpg",
    hasMedicine: false
  },
  {
    id: "amity-uz",
    name: "Amity University in Tashkent",
    location: "Uzbekistan",
    overall: 58.1,
    citations: 45.4,
    employability: 65.5,
    intlStudents: 28.0,
    teaching: 63.8,
    research: 49.2,
    subjects: ["Engineering", "Business"],
    languages: ["English"],
    tuition: "$3,200/year",
    description: "An Indian private branch university in Tashkent, delivering highly practical coursework in information technology, computer engineering, and tourism management.",
    history: [47, 55, 70, 92, 110],
    programs: ["B.Tech. Computer Science & Engineering", "B.Sc. Information Technology", "BBA Business Administration"],
    campusPhoto: "/university_images/Uzbekistan/Amity University in Tashkent image.jpg",
    logo: "/university_images/Uzbekistan/Amity University in Tashkent logo.jpg",
    hasMedicine: false
  },
  {
    id: "Turin-polytech",
    name: "Turin Polytechnic University in Tashkent",
    location: "Uzbekistan",
    overall: 57.8,
    citations: 44.2,
    employability: 69.1,
    intlStudents: 20.2,
    teaching: 62.5,
    research: 51.4,
    subjects: ["Engineering"],
    languages: ["English", "Italian"],
    tuition: "$3,500/year",
    description: "Established in 2009 in partnership with Politecnico di Torino (Italy), this university prepares elite automotive, mechanical, and civil engineers in Uzbekistan.",
    history: [48, 54, 68, 88, 102],
    programs: ["B.Sc. Mechanical Engineering (Automotive)", "B.Sc. Civil Engineering", "B.Sc. Computer Engineering"],
    campusPhoto: "/university_images/Uzbekistan/Turin Polytechnic University in Tashkent image.jpg",
    logo: "/university_images/Uzbekistan/Turin Polytechnic University in Tashkent logo.jpg",
    hasMedicine: false
  },
  {
    id: "inha-tashkent",
    name: "Inha University in Tashkent",
    location: "Uzbekistan",
    overall: 57.2,
    citations: 43.8,
    employability: 71.4,
    intlStudents: 24.5,
    teaching: 61.2,
    research: 50.5,
    subjects: ["Engineering", "Business"],
    languages: ["English"],
    tuition: "$3,600/year",
    description: "Created in cooperation with Inha University in South Korea. Features cutting-edge logistics, software engineering, and business administration programs taught fully in English.",
    history: [49, 53, 67, 84, 98],
    programs: ["B.Sc. Computer Science & Engineering", "B.Sc. Information & Communication Engineering", "B.Sc. Business & Logistics"],
    campusPhoto: "/university_images/Uzbekistan/Inha University in Tashkent image.jpg",
    logo: "/university_images/Uzbekistan/Inha University in Tashkent logo.jpg",
    hasMedicine: false
  },
  {
    id: "world-economy-univ",
    name: "University of World Economy and Diplomacy",
    location: "Uzbekistan",
    overall: 56.5,
    citations: 42.1,
    employability: 68.0,
    intlStudents: 31.2,
    teaching: 63.0,
    research: 48.8,
    subjects: ["Business", "Law", "Humanities"],
    languages: ["Uzbek", "English", "Russian"],
    tuition: "$2,800/year",
    description: "UWED is the elite academy for foreign service in Uzbekistan. It trains diplomats, international lawyers, and macroeconomists with extensive language training.",
    history: [50, 56, 72, 90, 108],
    programs: ["B.A. International Relations", "B.A. International Law", "M.A. Global Diplomacy"],
    campusPhoto: "/university_images/Uzbekistan/University of World Economy and Diplomacy image.jpg",
    logo: "/university_images/Uzbekistan/University of World Economy and Diplomacy logo.jpg",
    hasMedicine: false
  }
];

export interface Article {
  id: string;
  title: string;
  subtitle: string;
  source: string;
  date: string;
  contentSummary: string;
  image: string;
  readTime?: string;
  content?: string;
  category?: string;
  tags?: string[];
}

export const FEATURED_ARTICLES: Article[] = [
  {
    id: "uzbekistan-med",
    title: "Why Central Asia is the New Frontier for Medicine",
    subtitle: "Uzbekistan’s English-Medium Reforms Spark Recruitment Wave",
    source: "Asia Higher Ed Report",
    date: "May 20, 2026",
    readTime: "8 min read",
    contentSummary: "Standardized medical academies like Tashkent Medical Academy and Fergana State have lower tuition ($3,000–$3,800/year) and WHO-recognized certifications, drawing thousands of international medical aspirants annually.",
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "multilingual-shift",
    title: "The Multilingual Shift in Asian Higher Education",
    subtitle: "Branch Campuses Break Traditional Language Barriers",
    source: "Global Academic Outlook",
    date: "April 15, 2026",
    readTime: "6 min read",
    contentSummary: "From Inha and Webster in Tashkent to global collaborative institutes in Shenzhen, the rapid rise of English-only tracks is shifting student demographics, drawing focus away from European centers.",
    image: "/university_images/higher education.avif"
  },
  {
    id: "metric-weights-guide",
    title: "Rethinking Citations vs. Employability in Ranking Systems",
    subtitle: "Principal Frontend Architect Shares Tabular Recalculation Methods",
    source: "Institutional Analytics Quarterly",
    date: "March 2, 2026",
    readTime: "11 min read",
    contentSummary: "For-hire rankings often mask true career outcomes. A breakdown of why student recruitment teams must pivot to customized metrics and how to utilize client-side  weights to guide university advisory.",
    image: "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?auto=format&fit=crop&w=600&q=80"
  }
];
